# Generated by Django 4.0.2 on 2022-02-04 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SCRAPPER', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(max_length=300)),
                ('base_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCRAPPER.vocabulary')),
            ],
        ),
    ]
